name: Example workflow for S3 Deploy
on:
  push:
    branches:
      - 'master'
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: [18.3.0]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
        - uses: actions/checkout@v3
        - name: Use node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'
        - name: Install dependencies
          run: export NODE_OPTIONS=--openssl-legacy-provider && yarn install
        - name: Build
          run: export NODE_OPTIONS=--openssl-legacy-provider && yarn build
        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket-region: us-east-1
            # deployment is set up in the aws-infra repo, you'll wanna get these values from cloudformation
            bucket: alternativepiano.com-production
            dist-id: E3VRY0JF2WM6XA
            invalidation: /
            delete-removed: true
            no-cache: true
            private: true
            filesToInclude: ".*/*,*/*,**"
